# Generated by Django 5.0.2 on 2024-02-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='images/%y/%m/%d')),
                ('username', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('firstName', models.CharField(max_length=15)),
                ('lastName', models.CharField(max_length=15)),
                ('Address', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=8)),
                ('country', models.CharField(max_length=5)),
                ('phoneNumber', models.BigIntegerField(max_length=10)),
                ('companyName', models.CharField(max_length=15)),
            ],
        ),
    ]
