# Generated by Django 5.0.2 on 2024-02-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='postalcode',
            field=models.IntegerField(default=1234),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phoneNumber',
            field=models.BigIntegerField(),
        ),
    ]
