# Generated by Django 5.0.2 on 2024-02-18 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_userinfo_postalcode_alter_userinfo_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='photo',
            field=models.ImageField(blank=True, upload_to='dashboard'),
        ),
    ]
