# Generated by Django 5.0.2 on 2024-02-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_alter_userinfo_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usrname', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
    ]
